# __init__.py
# tooltip – VisioStar's ComfyUI nodes

from .AspectLatentSelector import NODE_CLASS_MAPPINGS as ALS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ALS_NAMES
from .DeepseekDualPromptComposer import NODE_CLASS_MAPPINGS as DSD_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DSD_NAMES
from .PromptListStandalone import NODE_CLASS_MAPPINGS as PLS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PLS_NAMES
from .SizeListLatentGenerator import NODE_CLASS_MAPPINGS as SLLG_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SLLG_NAMES
from .ByteDanceSeedreamSizeList import NODE_CLASS_MAPPINGS as BDSL_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BDSL_NAMES

# 合并所有节点的映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(ALS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(DSD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PLS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SLLG_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BDSL_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(ALS_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(DSD_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(PLS_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(SLLG_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(BDSL_NAMES)
